### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zuixik** [Jakubson/JPremiumCleared#18]
```
[13:59:54 WARN]: Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=LoginResult(id=ad967e2b980843a48eab30582a54b413, name=Zuixik, properties=[LoginResult.Property(name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTYyNzA2MzE5OTEzMCwKICAicHJvZmlsZUlkIiA6ICJhZDk2N2UyYjk4MDg0M2E0OGVhYjMwNTgyYTU0YjQxMyIsCiAgInByb2ZpbGVOYW1lIiA6ICJadWl4aWsiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRkN2IyODc5YWVkODc2YzNjYjcwNmRkZTQwY2UzNTJkY2IxODZiZWFmODY0Y2JmZjQyNDliZGQ0Y2U2ZDVkMCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9, signature=LUEkK5giRR9lhxywH4N3EgFPyI/xCBvg8A1tEnsErTnARvctTXgB3HyJC2rv9q3RPIFWRcWoRFrTBfqep53c6Pt8mHBvimHkFyc+ucqhz5JVWEbA6GfYdk2yfFpvzVJf6fYM2wm90OTPlZjER/Gw//yQ2hXCiZ8Z+KlGg9VgLjfW9eJlrnggjcOEhHWzC0BG8Hkity9QlLy38vcCMDI3SDPH93S7j4FXczQpAC4jHSRt0h6Hn51GEghkMXFPdgV+h680oeOW49I9pjXl78OXkDUkT2IfrxJFZ8Njh8etvbNpAz9c5XEzedoyyHCB7cPjDHu8Zi/Y5fEWItJQIxjJFxm7107U4+6IWXyT7i6VubEVw2qx2v5+EYh7AP43AUSjfNFUD67ob9P4yM75ZQ2KagS4M0dXxyjssuPAUKdctdqAFzRk7qrYxn6dlONeZFfLDo7XzdNOi/cbKA7B5LKgi7xQYP+GBjmbF4953IDsB25JMgcMWAOWerCR8RyOdOxnbXdJcoRRqVe6X9NlC4GjWve1RsClg3pJXRBzdcZlSJAjlqM0fNEAKsE0/YXT540QPk8k5jChbDrodjUdLP/5QgBOGPvXZ/qbMGij7Sul7oLAa/2lD/b0gzJDD0D1qbw4jhMotytqbgsQq3QhzZpzpM67kzU/0XGtPngE1udvObU=)]), connection=[/0.0.0.0|Zuixik] <-> InitialHandler) to listener com.jakub.premium.c.c@17063c32
java.lang.NoSuchFieldException: uniqueId
        at java.lang.Class.getDeclaredField(Unknown Source) ~[?:?]
        at com.jakub.premium.c.c.a(Unknown Source) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:615) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:74) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:507) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:492) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
        at java.lang.Thread.run(Unknown Source) [?:?]
[13:59:54 INFO]: [Zuixik] disconnected with: Kicked whilst connecting to Authme: [»] Please join to the server via mc.example.com!

```

**Comment by Jakubson** [comment]
Hu, I give support only on SpigotMC. Please contact with me there: https://www.spigotmc.org/conversations/add?to=Jakubson
