### ISSUE TITLE
Could not load JPremium assets!

### ISSUE THREAD

**Issue by skigrex** [Jakubson/JPremiumCleared#20]
hello, i just change the host amd when i try to start the bungee it gave me an error, i try uploading to the new version, but nothing happen, i am using the newest version of watterfall, mariadb and Pterodactyl

**Comment by skigrex** [comment]
here you have the entire issue:
[22:35:22 ERROR] [JPremium]: Could not load JPremium assets!
[22:35:22 ERROR]: org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
[22:35:22 ERROR]:       at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.scanner.ScannerImpl.scanComment(ScannerImpl.java:1262)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1231)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:602)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
[22:35:22 ERROR]:       at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:111)
[22:35:22 ERROR]:       at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:79)
[22:35:22 ERROR]:       at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:71)
[22:35:22 ERROR]:       at com.jakub.premium.d.i.a(Unknown Source)
[22:35:22 ERROR]:       at com.jakub.premium.JPremium.onEnable(Unknown Source)
[22:35:22 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[22:35:22 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[22:35:22 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[22:35:22 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[22:35:22 ERROR]: Caused by: java.nio.charset.MalformedInputException: Input length = 1
[22:35:22 ERROR]:       at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)
[22:35:22 ERROR]:       at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
[22:35:22 ERROR]:       at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
[22:35:22 ERROR]:       at java.base/java.io.InputStreamReader.read(Unknown Source)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125)
[22:35:22 ERROR]:       at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
[22:35:22 ERROR]:       ... 32 more

**Comment by Jakubson** [comment]
Generate new JPremium configuration files and configure them again.

**Comment by skigrex** [comment]
i did that and it didn t work at all

**Comment by Jakubson** [comment]
Your JPremium configuration or messages file contains some illegal chars or they are wrongly encoded. You can open them using some text editor (like Notepad++ or SublimeText) and change encoding to UTF-8.

**Comment by skigrex** [comment]
i think that i found the error, i think that i am using a invalid character for the mysql password, this one: ·

**Comment by skigrex** [comment]
i didn' t change it but i just realice that the error is diferent now

[16:03:29 ERROR] [JPremium]: Could not load JPremium assets!
[16:03:29 ERROR]: expected '<document start>', but found '<block mapping start>'
[16:03:29 ERROR]:  in 'reader', line 10, column 1:
[16:03:29 ERROR]:     version: 'CLEARED-Bungee-1.12.2'
[16:03:29 ERROR]:     ^
[16:03:29 ERROR]: 
[16:03:29 ERROR]:       at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:256)
[16:03:29 ERROR]:       at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[16:03:29 ERROR]:       at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155)
[16:03:29 ERROR]:       at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:149)
[16:03:29 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[16:03:29 ERROR]:       at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[16:03:29 ERROR]:       at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
[16:03:29 ERROR]:       at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:111)
[16:03:29 ERROR]:       at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:79)
[16:03:29 ERROR]:       at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:71)
[16:03:29 ERROR]:       at com.jakub.premium.d.i.a(Unknown Source)
[16:03:29 ERROR]:       at com.jakub.premium.JPremium.onEnable(Unknown Source)
[16:03:29 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[16:03:29 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[16:03:29 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[16:03:29 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)


i tried uploading a new configuration again and copying that part, but the error is still there

**Comment by Jakubson** [comment]
Now you have an YAML syntax error. Check line 10 and 9. Make sure that you do not have any unnecessary chars.
If you are not able to solve it, send your configuration file, but hide all sensible data (like an access toekn, MySQL credentials).

**Comment by skigrex** [comment]
i am going to cry, i solved it and it give me back another error, but now i think that it is a problem of the mysql, i don t really now

[18:01:44 ERROR]: [main] INFO shaded.com.zaxxer.hikari.HikariDataSource - JPremium - Starting...
[18:01:45 INFO] [ViaVersion]: Finished mapping loading, shutting down loader executor!
[18:01:46 ERROR]: [main] ERROR shaded.com.zaxxer.hikari.pool.HikariPool - JPremium - Exception during pool initialization.
[18:01:46 ERROR]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[18:01:46 ERROR]: 
[18:01:46 ERROR]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:01:46 ERROR]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[18:01:46 ERROR]:       at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[18:01:46 ERROR]:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
[18:01:46 ERROR]:       at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:01:46 ERROR]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
[18:01:46 ERROR]:       at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.HikariPool.<init>(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.HikariDataSource.<init>(Unknown Source)
[18:01:46 ERROR]:       at com.jakub.premium.d.j.<init>(Unknown Source)
[18:01:46 ERROR]:       at com.jakub.premium.JPremium.onEnable(Unknown Source)
[18:01:46 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[18:01:46 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[18:01:46 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[18:01:46 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[18:01:46 ERROR]: Caused by: java.net.ConnectException: Connection refused
[18:01:46 ERROR]:       at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[18:01:46 ERROR]:       at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
[18:01:46 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
[18:01:46 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.net.Socket.connect(Unknown Source)
[18:01:46 ERROR]:       at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
[18:01:46 ERROR]:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299)
[18:01:46 ERROR]:       ... 26 more
[18:01:46 ERROR] [JPremium]: Could not load JPremium assets!
[18:01:46 ERROR]: shaded.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
[18:01:46 ERROR]: 
[18:01:46 ERROR]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.HikariPool.<init>(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.HikariDataSource.<init>(Unknown Source)
[18:01:46 ERROR]:       at com.jakub.premium.d.j.<init>(Unknown Source)
[18:01:46 ERROR]:       at com.jakub.premium.JPremium.onEnable(Unknown Source)
[18:01:46 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[18:01:46 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[18:01:46 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[18:01:46 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[18:01:46 ERROR]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[18:01:46 ERROR]: 
[18:01:46 ERROR]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:01:46 ERROR]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[18:01:46 ERROR]:       at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[18:01:46 ERROR]:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
[18:01:46 ERROR]:       at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:01:46 ERROR]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[18:01:46 ERROR]:       at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
[18:01:46 ERROR]:       at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(Unknown Source)
[18:01:46 ERROR]:       at shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(Unknown Source)
[18:01:46 ERROR]:       ... 9 more
[18:01:46 ERROR]: Caused by: java.net.ConnectException: Connection refused
[18:01:46 ERROR]:       at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[18:01:46 ERROR]:       at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
[18:01:46 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
[18:01:46 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
[18:01:46 ERROR]:       at java.base/java.net.Socket.connect(Unknown Source)
[18:01:46 ERROR]:       at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
[18:01:46 ERROR]:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299)
[18:01:46 ERROR]:       ... 26 more

**Comment by Jakubson** [comment]
I am closing this ticket because now it is not related with JPremium, but with your MySQL database. Read this wiki page: https://github.com/Jakubson/JPremiumCleared/wiki#database-issues
